//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombinedData
    {
        public int ID { get; set; }
        public Nullable<int> Record_Number { get; set; }
        public Nullable<double> TOWSensor { get; set; }
        public Nullable<double> TOWCalc { get; set; }
        public Nullable<double> SurfaceTemp { get; set; }
        public Nullable<int> TimeInterval { get; set; }
        public Nullable<double> ATM_RH { get; set; }
        public Nullable<double> ATM_Temp { get; set; }
        public Nullable<double> Rain { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> DataType { get; set; }
    }
}
