//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetData
    {
        public int ID { get; set; }
        public Nullable<int> RECORD_NUM { get; set; }
        public Nullable<double> DSTO_TOW_1_mA_ { get; set; }
        public Nullable<double> THERMISTOR_1_TEMP { get; set; }
        public Nullable<double> Time_interval_s { get; set; }
        public Nullable<double> HUMIDITY_1 { get; set; }
        public Nullable<double> TEMPERATURE_1 { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<int> Location { get; set; }
    }
}
