//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorrosionModelEntities : DbContext
    {
        public CorrosionModelEntities()
            : base("name=CorrosionModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CombinedData> CombinedDatas { get; set; }
        public virtual DbSet<MetData> MetDatas { get; set; }
        public virtual DbSet<t_Base_Properties> t_Base_Properties { get; set; }
        public virtual DbSet<t_Flights> t_Flights { get; set; }
        public virtual DbSet<t_History> t_History { get; set; }
        public virtual DbSet<t_Images> t_Images { get; set; }
        public virtual DbSet<t_Location> t_Location { get; set; }
        public virtual DbSet<t_Materials> t_Materials { get; set; }
        public virtual DbSet<t_Parameter_List> t_Parameter_List { get; set; }
        public virtual DbSet<t_Parameters> t_Parameters { get; set; }
        public virtual DbSet<t_Salt_Composition> t_Salt_Composition { get; set; }
        public virtual DbSet<t_Sensor_Data> t_Sensor_Data { get; set; }
        public virtual DbSet<t_Pollutant_Deposition> t_Pollutant_Deposition { get; set; }
    }
}
