//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Base_Properties
    {
        public int Location { get; set; }
        public int Month { get; set; }
        public Nullable<double> Salt_dep { get; set; }
        public Nullable<double> pH { get; set; }
        public Nullable<double> Conc { get; set; }
    }
}
