//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flights
    {
        public string Aircraft_Tail { get; set; }
        public System.DateTime Arrival_Date { get; set; }
        public int From_Location { get; set; }
        public System.DateTime Departure_Date { get; set; }
        public int Destination_Location { get; set; }
        public int Route { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual t_Location t_Location { get; set; }
        public virtual t_Location t_Location1 { get; set; }
    }
}
