//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_History
    {
        public string Tail_Number { get; set; }
        public int Location { get; set; }
        public System.DateTime Arrival_Time { get; set; }
        public System.DateTime Departure_Time { get; set; }
    
        public virtual t_Location t_Location { get; set; }
    }
}
