//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Pollutant_Deposition
    {
        public int Location { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<double> Cl { get; set; }
        public Nullable<double> Na { get; set; }
        public Nullable<double> Mg { get; set; }
        public Nullable<double> Ca { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<double> NH4 { get; set; }
        public Nullable<double> NO3 { get; set; }
        public Nullable<double> SO4 { get; set; }
        public Nullable<double> TotalSalt { get; set; }
        public Nullable<double> pH { get; set; }
        public Nullable<double> RainConc { get; set; }
        public Nullable<double> RainDeposit { get; set; }
    
        public virtual t_Location t_Location { get; set; }
    }
}
