//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACMAN
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Salt_Composition
    {
        public int Location { get; set; }
        public int Month { get; set; }
        public Nullable<double> NaCl { get; set; }
        public Nullable<double> MgC12 { get; set; }
        public Nullable<double> Na2S04 { get; set; }
        public Nullable<double> CaC12 { get; set; }
        public Nullable<double> KCI { get; set; }
        public Nullable<double> NH4NO3 { get; set; }
        public Nullable<double> NH42SO4 { get; set; }
        public Nullable<double> MgSO4 { get; set; }
        public Nullable<double> K2SO4 { get; set; }
        public Nullable<double> CaSO4 { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> MinSalts { get; set; }
        public Nullable<double> HSMass { get; set; }
        public Nullable<double> HNMass { get; set; }
    }
}
